In [659]:
import pandas as pd
import csv

In [660]:
df=pd.read_csv('EMP_TEMP_SEX_AGE_ECO_NB_A-filtered-2024-09-23.csv')
df

,ref_area,source,indicator,sex,classif1,classif2,time,obs_value,obs_status,note_classif,note_indicator,note_source
0,AFG,BA:15715,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_TOTAL,ECO_AGGREGATE_TOTAL,2021,1829.046,NaN,NaN,NaN,R1:3513_S3:8
1,AFG,BA:15715,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_TOTAL,ECO_AGGREGATE_AGR,2021,1280.255,NaN,NaN,NaN,R1:3513_S3:8
2,AFG,BA:15715,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_TOTAL,ECO_AGGREGATE_MAN,2021,293.039,NaN,NaN,NaN,R1:3513_S3:8
3,AFG,BA:15715,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_TOTAL,ECO_AGGREGATE_CON,2021,12.618,U,NaN,NaN,R1:3513_S3:8
4,AFG,BA:15715,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_TOTAL,ECO_AGGREGATE_MEL,2021,0.000,NaN,NaN,NaN,R1:3513_S3:8
...,...,...,...,...,...,...,...,...,...,...,...,...
102735,ZWE,BA:1823,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_YGE65,ECO_AGGREGATE_MAN,2011,2.825,U,NaN,I11:264,R1:3513
102736,ZWE,BA:1823,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_YGE65,ECO_AGGREGATE_CON,2011,NaN,U,NaN,I11:264,R1:3513
102737,ZWE,BA:1823,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_YGE65,ECO_AGGREGATE_MEL,2011,NaN,U,NaN,I11:264,R1:3513
102738,ZWE,BA:1823,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_YGE65,ECO_AGGREGATE_MKT,2011,5.705,B,NaN,I11:264,R1:3513
102739,ZWE,BA:1823,EMP_TEMP_SEX_AGE_ECO_NB,SEX_F,AGE_10YRBANDS_YGE65,ECO_AGGREGATE_PUB,2011,2.099,U,NaN,I11:264,R1:3513

In [661]:
df=df.drop(['source', 'sex','note_classif','obs_status', 'note_source', 'note_indicator','indicator'], axis=1)

In [662]:
df

       ref_area             classif1             classif2  time  obs_value
0           AFG  AGE_10YRBANDS_TOTAL  ECO_AGGREGATE_TOTAL  2021   1829.046
1           AFG  AGE_10YRBANDS_TOTAL    ECO_AGGREGATE_AGR  2021   1280.255
2           AFG  AGE_10YRBANDS_TOTAL    ECO_AGGREGATE_MAN  2021    293.039
3           AFG  AGE_10YRBANDS_TOTAL    ECO_AGGREGATE_CON  2021     12.618
4           AFG  AGE_10YRBANDS_TOTAL    ECO_AGGREGATE_MEL  2021      0.000
...         ...                  ...                  ...   ...        ...
102735      ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_MAN  2011      2.825
102736      ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_CON  2011        NaN
102737      ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_MEL  2011        NaN
102738      ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_MKT  2011      5.705
102739      ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_PUB  2011      2.099

[102740 rows x 5 columns]

In [663]:
df= df.rename(columns={'obs_value': 'number_worker'})
df= df.rename(columns={'time': 'year'})
df= df.rename(columns={'ref_area': 'country'})
df= df.rename(columns={'classif1': 'age_group'})
df= df.rename(columns={'classif2': 'job_category'})

number of employees in thousands

In [664]:
df

       country            age_group         job_category  year  number_worker
0          AFG  AGE_10YRBANDS_TOTAL  ECO_AGGREGATE_TOTAL  2021       1829.046
1          AFG  AGE_10YRBANDS_TOTAL    ECO_AGGREGATE_AGR  2021       1280.255
2          AFG  AGE_10YRBANDS_TOTAL    ECO_AGGREGATE_MAN  2021        293.039
3          AFG  AGE_10YRBANDS_TOTAL    ECO_AGGREGATE_CON  2021         12.618
4          AFG  AGE_10YRBANDS_TOTAL    ECO_AGGREGATE_MEL  2021          0.000
...        ...                  ...                  ...   ...            ...
102735     ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_MAN  2011          2.825
102736     ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_CON  2011            NaN
102737     ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_MEL  2011            NaN
102738     ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_MKT  2011          5.705
102739     ZWE  AGE_10YRBANDS_YGE65    ECO_AGGREGATE_PUB  2011          2.099

[102740 rows x 5 columns]

27 job activity

In [665]:
equivalence_dict_job = {
'ECO_AGGREGATE_TOTAL' : 'Total',
'ECO_AGGREGATE_AGR' : 'Agriculture',
'ECO_AGGREGATE_MAN' : 'Manufacturing',
'ECO_AGGREGATE_CON' : 'Construction',
'ECO_AGGREGATE_MEL' : 'Mining_and_quarrying',
'ECO_AGGREGATE_MKT' : 'Market_services',
'ECO_AGGREGATE_PUB' : 'Non_market_services',
'ECO_AGGREGATE_X' : 'Non_classified'
}

df['job_category'] = df['job_category'].replace(equivalence_dict_job)

In [666]:
equivalence_dict_age = {
    'AGE_10YRBANDS_Y15-24': '15_24',
    'AGE_10YRBANDS_Y25-34': '25_34',
    'AGE_10YRBANDS_Y35-44': '35_44',
    'AGE_10YRBANDS_Y45-54': '45_54',
    'AGE_10YRBANDS_Y55-64': '55_64',
    'AGE_10YRBANDS_YGE65': '65+',
    'AGE_10YRBANDS_TOTAL': 'Total'
}

df['age_group_simp'] = df['age_group'].replace(equivalence_dict_age)

df=df.drop(['age_group'], axis=1)

In [667]:
df

       country          job_category  year  number_worker age_group_simp
0          AFG                 Total  2021       1829.046          Total
1          AFG           Agriculture  2021       1280.255          Total
2          AFG         Manufacturing  2021        293.039          Total
3          AFG          Construction  2021         12.618          Total
4          AFG  Mining_and_quarrying  2021          0.000          Total
...        ...                   ...   ...            ...            ...
102735     ZWE         Manufacturing  2011          2.825            65+
102736     ZWE          Construction  2011            NaN            65+
102737     ZWE  Mining_and_quarrying  2011            NaN            65+
102738     ZWE       Market_services  2011          5.705            65+
102739     ZWE   Non_market_services  2011          2.099            65+

[102740 rows x 5 columns]

In [668]:
df.to_csv('EMP_CAT_standard_.csv')

simplify

In [669]:
# Count missing values in each column
print('Number of missing value by column')
missing_values_per_column = df.isnull().sum()

print(missing_values_per_column)

Number of missing value by column
country               0
job_category          0
year                  0
number_worker     10490
age_group_simp        0
dtype: int64

In [670]:
df = df.fillna(-1)

In [671]:
df['number_worker']=(df['number_worker']*1000).astype(int)

In [672]:
df.loc[df['number_worker'] <= 0, 'number_worker'] = -1

In [673]:
df.to_csv('EMP_CAT_standard.csv')

In [674]:
df

       country          job_category  year  number_worker age_group_simp
0          AFG                 Total  2021        1829046          Total
1          AFG           Agriculture  2021        1280255          Total
2          AFG         Manufacturing  2021         293039          Total
3          AFG          Construction  2021          12618          Total
4          AFG  Mining_and_quarrying  2021             -1          Total
...        ...                   ...   ...            ...            ...
102735     ZWE         Manufacturing  2011           2825            65+
102736     ZWE          Construction  2011             -1            65+
102737     ZWE  Mining_and_quarrying  2011             -1            65+
102738     ZWE       Market_services  2011           5705            65+
102739     ZWE   Non_market_services  2011           2099            65+

[102740 rows x 5 columns]

Creation of derived data  
--> most popular job category per country

In [675]:

# Step 1: Filter for age_group_simp == 'Total' and job_category != 'Total'
filtered_df = df[(df['age_group_simp'] == 'Total') & (df['job_category'] != 'Total')]

In [676]:

total_workers = filtered_df.groupby(['country', 'year', 'job_category'], as_index=False)['number_worker'].sum()
most_popular = total_workers.loc[total_workers.groupby(['country', 'year'])['number_worker'].idxmax()]

In [686]:
most_popular

      country  year job_category  number_worker
0         AFG  2008  Agriculture        1950196
7         AFG  2012  Agriculture         565217
13        AFG  2014  Agriculture         953930
20        AFG  2017  Agriculture         903558
27        AFG  2020  Agriculture         598464
...       ...   ...          ...            ...
12926     ZWE  2011  Agriculture        1954399
12932     ZWE  2014  Agriculture        2272865
12939     ZWE  2019  Agriculture        1662598
12946     ZWE  2021  Agriculture        1561818
12953     ZWE  2022  Agriculture        1591528

[1965 rows x 4 columns]

In [700]:
df['most_popular_job_cat'] = 'None'

In [701]:
df

,country,job_category,year,number_worker,age_group_simp,most_popular_job_cat
0,AFG,Total,2021,1829046,Total,None
1,AFG,Total,2021,1829046,Total,None
2,AFG,Total,2021,1829046,Total,None
3,AFG,Total,2021,1829046,Total,None
4,AFG,Total,2021,1829046,Total,None
...,...,...,...,...,...,...
9052599,ZWE,Non_market_services,2011,2099,65+,None
9052600,ZWE,Non_market_services,2011,2099,65+,None
9052601,ZWE,Non_market_services,2011,2099,65+,None
9052602,ZWE,Non_market_services,2011,2099,65+,None
9052603,ZWE,Non_market_services,2011,2099,65+,None

In [702]:
# Step 3: Merge the most popular job category back into the original DataFrame
df_with_popular_category = filtered_df.merge(
    most_popular[['country', 'year', 'job_category', 'number_worker']],
    on=['country', 'year'],
    how='left',
    suffixes=('', '_most_popular')
)

# Rename the new column to 'most_popular_job_cat'
df_with_popular_category.rename(columns={'job_category_most_popular': 'most_popular_job_cat'}, inplace=True)

In [699]:
df_with_popular_category.head(100)

,country,job_category,year,number_worker,age_group_simp,most_popular_job_cat,number_worker_most_popular
0,AFG,Agriculture,2021,1280255,Total,Agriculture,1280255
1,AFG,Manufacturing,2021,293039,Total,Agriculture,1280255
2,AFG,Construction,2021,12618,Total,Agriculture,1280255
3,AFG,Mining_and_quarrying,2021,-1,Total,Agriculture,1280255
4,AFG,Market_services,2021,18656,Total,Agriculture,1280255
...,...,...,...,...,...,...,...
95,ALB,Manufacturing,2018,77091,Total,Agriculture,227904
96,ALB,Construction,2018,2743,Total,Agriculture,227904
97,ALB,Mining_and_quarrying,2018,4072,Total,Agriculture,227904
98,ALB,Market_services,2018,112268,Total,Agriculture,227904
99,ALB,Non_market_services,2018,115444,Total,Agriculture,227904

In [704]:
# Faire une jointure (merge) sur les colonnes 'country' et 'year'
df_merged = pd.merge(df, df_with_popular_category, on=['country', 'year'], how='left')

print(df_merged)

MemoryError: Unable to allocate 457. MiB for an array with shape (59915236,) and data type int64

In [681]:
df.to_csv('dataset_clean_with_derived_data_job_cat.csv')

KeyboardInterrupt:

In [709]:
# Initialize an empty dictionary to store the values
popular_job_dict = {}

# Loop through each row in df_with_popular_category
for idx, row in df_with_popular_category.iterrows():
    country = row['country']
    year = row['year']
    most_popular_job_cat = row['most_popular_job_cat']
    
    # Store the value in the dictionary only if it's not already present for that country and year
    if country not in popular_job_dict:
        popular_job_dict[country] = {}
    
    # Check if the year is already present and if the value is identical; only store if it's new/different
    if year not in popular_job_dict[country] or popular_job_dict[country][year] != most_popular_job_cat:
        popular_job_dict[country][year] = most_popular_job_cat

# The result is a dictionary with countries and years, storing unique most_popular_job_cat values.
popular_job_dict

{'AFG': {2021: 'Agriculture',
  2020: 'Agriculture',
  2017: 'Agriculture',
  2014: 'Agriculture',
  2012: 'Agriculture',
  2008: 'Agriculture'},
 'AGO': {2021: 'Agriculture',
  2019: 'Agriculture',
  2014: 'Agriculture',
  2011: 'Agriculture',
  2009: 'Agriculture',
  2004: 'Agriculture'},
 'ALB': {2021: 'Agriculture',
  2019: 'Agriculture',
  2018: 'Agriculture',
  2017: 'Agriculture',
  2016: 'Agriculture',
  2015: 'Agriculture',
  2014: 'Agriculture',
  2013: 'Agriculture',
  2012: 'Agriculture',
  2011: 'Agriculture',
  2010: 'Agriculture',
  2009: 'Agriculture',
  2008: 'Agriculture',
  2007: 'Agriculture'},
 'ARE': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services'},
 'ARG': {2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services'},
 'ARM': {2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Agriculture',
  2018: 'Agriculture',
  2017: 'Non_market_services',
  2016: 'Agriculture',
  2015: 'Agriculture',
  2014: 'Agriculture',
  2013: 'Agriculture',
  2012: 'Agriculture',
  2011: 'Agriculture',
  2010: 'Agriculture',
  2009: 'Agriculture',
  2008: 'Agriculture',
  2007: 'Agriculture'},
 'AUS': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Market_services'},
 'AUT': {2023: 'Market_services',
  2022: 'Market_services',
  2021: 'Market_services',
  2020: 'Market_services',
  2019: 'Market_services',
  2018: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2010: 'Market_services',
  2009: 'Market_services',
  2008: 'Market_services',
  2007: 'Market_services',
  2006: 'Market_services',
  2005: 'Market_services',
  2004: 'Market_services',
  2003: 'Market_services',
  2002: 'Market_services',
  2001: 'Market_services',
  2000: 'Market_services'},
 'BDI': {2020: 'Agriculture', 2014: 'Agriculture'},
 'BEL': {2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'BEN': {2022: 'Agriculture', 2019: 'Market_services', 2011: 'Agriculture'},
 'BFA': {2023: 'Market_services',
  2022: 'Agriculture',
  2019: 'Agriculture',
  2018: 'Market_services',
  2014: 'Market_services'},
 'BGD': {2022: 'Agriculture',
  2017: 'Agriculture',
  2013: 'Agriculture',
  2010: 'Agriculture',
  2006: 'Agriculture'},
 'BGR': {2022: 'Market_services',
  2021: 'Market_services',
  2020: 'Market_services',
  2019: 'Market_services',
  2018: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2010: 'Market_services',
  2009: 'Market_services',
  2008: 'Market_services',
  2007: 'Market_services',
  2006: 'Market_services',
  2005: 'Market_services',
  2004: 'Market_services',
  2003: 'Non_market_services',
  2002: 'Market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'BHS': {2019: 'Market_services'},
 'BIH': {2023: 'Market_services',
  2022: 'Market_services',
  2021: 'Market_services',
  2020: 'Non_market_services',
  2019: 'Market_services',
  2018: 'Non_market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Non_market_services',
  2014: 'Market_services',
  2013: 'Non_market_services',
  2012: 'Market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Market_services',
  2008: 'Market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2001: 'Non_market_services'},
 'BLR': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services'},
 'BLZ': {2019: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services'},
 'BOL': {2023: 'Market_services',
  2022: 'Market_services',
  2021: 'Market_services',
  2020: 'Market_services',
  2019: 'Market_services',
  2018: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2009: 'Market_services',
  2008: 'Market_services',
  2007: 'Agriculture',
  2006: 'Agriculture',
  2005: 'Agriculture',
  2002: 'Agriculture',
  2001: 'Agriculture',
  2000: 'Agriculture'},
 'BRA': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services'},
 'BRB': {2019: 'Market_services',
  2018: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services'},
 'BRN': {2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2014: 'Non_market_services'},
 'BTN': {2023: 'Agriculture',
  2022: 'Agriculture',
  2021: 'Agriculture',
  2020: 'Agriculture',
  2019: 'Agriculture',
  2018: 'Agriculture'},
 'BWA': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2009: 'Non_market_services',
  2006: 'Non_market_services'},
 'CAN': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'CHE': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'CHL': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2006: 'Non_market_services',
  2003: 'Non_market_services',
  2000: 'Non_market_services'},
 'CHN': {2000: 'Agriculture'},
 'CIV': {2022: 'Agriculture',
  2019: 'Market_services',
  2017: 'Market_services',
  2016: 'Agriculture',
  2013: 'Agriculture',
  2012: 'Market_services'},
 'CMR': {2021: 'Agriculture', 2014: 'Agriculture', 2007: 'Agriculture'},
 'COD': {2012: 'Agriculture', 2005: 'Agriculture'},
 'COG': {2009: 'Market_services', 2005: 'Agriculture'},
 'COK': {2019: 'Market_services', 2016: 'Market_services'},
 'COL': {2023: 'Market_services',
  2022: 'Market_services',
  2021: 'Market_services',
  2020: 'Market_services',
  2019: 'Market_services',
  2018: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2010: 'Market_services',
  2009: 'Market_services',
  2008: 'Market_services',
  2007: 'Market_services',
  2005: 'Market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services'},
 'COM': {2021: 'Non_market_services',
  2014: 'Agriculture',
  2004: 'Agriculture'},
 'CPV': {2015: 'Non_market_services', 2009: 'Non_market_services'},
 'CRI': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services'},
 'CYP': {2022: 'Market_services',
  2021: 'Market_services',
  2020: 'Market_services',
  2019: 'Market_services',
  2018: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2010: 'Market_services',
  2009: 'Market_services',
  2008: 'Market_services',
  2007: 'Market_services',
  2006: 'Market_services',
  2005: 'Market_services',
  2004: 'Market_services',
  2003: 'Market_services',
  2002: 'Market_services',
  2001: 'Market_services',
  2000: 'Market_services'},
 'CZE': {2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2010: 'Market_services',
  2009: 'Market_services',
  2008: 'Market_services'},
 'DEU': {2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'DJI': {2017: 'Non_market_services'},
 'DNK': {2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'DOM': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'ECU': {2023: 'Market_services',
  2022: 'Market_services',
  2021: 'Market_services',
  2020: 'Market_services',
  2019: 'Market_services',
  2018: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2010: 'Market_services',
  2009: 'Market_services',
  2008: 'Market_services',
  2007: 'Market_services',
  2006: 'Market_services',
  2005: 'Market_services',
  2004: 'Market_services',
  2003: 'Market_services',
  2001: 'Market_services'},
 'EGY': {2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2013: 'Agriculture',
  2012: 'Non_market_services',
  2011: 'Agriculture',
  2010: 'Agriculture',
  2009: 'Agriculture',
  2008: 'Agriculture'},
 'ESP': {2023: 'Market_services',
  2022: 'Market_services',
  2021: 'Market_services',
  2020: 'Market_services',
  2019: 'Market_services',
  2018: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2010: 'Market_services',
  2009: 'Market_services',
  2008: 'Market_services',
  2007: 'Market_services',
  2006: 'Market_services',
  2005: 'Market_services',
  2004: 'Market_services',
  2003: 'Market_services',
  2002: 'Market_services',
  2001: 'Market_services',
  2000: 'Market_services'},
 'EST': {2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Market_services',
  2019: 'Market_services',
  2018: 'Market_services',
  2017: 'Market_services',
  2016: 'Market_services',
  2015: 'Market_services',
  2014: 'Market_services',
  2013: 'Market_services',
  2012: 'Market_services',
  2011: 'Market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'ETH': {2021: 'Agriculture', 2013: 'Agriculture', 2005: 'Agriculture'},
 'FIN': {2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'FJI': {2016: 'Market_services',
  2011: 'Agriculture',
  2005: 'Market_services'},
 'FRA': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'FSM': {2014: 'Non_market_services'},
 'GBR': {2023: 'Non_market_services',
  2022: 'Non_market_services',
  2021: 'Non_market_services',
  2020: 'Non_market_services',
  2019: 'Non_market_services',
  2018: 'Non_market_services',
  2017: 'Non_market_services',
  2016: 'Non_market_services',
  2015: 'Non_market_services',
  2014: 'Non_market_services',
  2013: 'Non_market_services',
  2012: 'Non_market_services',
  2011: 'Non_market_services',
  2010: 'Non_market_services',
  2009: 'Non_market_services',
  2008: 'Non_market_services',
  2007: 'Non_market_services',
  2006: 'Non_market_services',
  2005: 'Non_market_services',
  2004: 'Non_market_services',
  2003: 'Non_market_services',
  2002: 'Non_market_services',
  2001: 'Non_market_services',
  2000: 'Non_market_services'},
 'GEO': {2020: 'Agriculture',
  2019: 'Agriculture',
  2018: 'Agriculture',
  2017: 'Agriculture',
  2016: 'Agriculture',
  2015: 'Agriculture',
  2014: 'Agriculture',

In [711]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9052604 entries, 0 to 9052603
Data columns (total 6 columns):
 #   Column                Dtype
---  ------                -----
 0   country               object
 1   job_category          object
 2   year                  int64
 3   number_worker         int32
 4   age_group_simp        object
 5   most_popular_job_cat  object
dtypes: int32(1), int64(1), object(4)
memory usage: 379.9+ MB

In [712]:
# Loop through each row in df
for idx, row in df.iterrows():
    country = row['country']
    year = row['year']
    age_group = row['age_group_simp']
    
    # Check if 'age_group_simp' is 'Total' and if the country and year exist in the dictionary
    if age_group == 'Total' and country in popular_job_dict and year in popular_job_dict[country]:
        # Update 'most_popular_job_cat' to the corresponding value in the dictionary
        df.at[idx, 'most_popular_job_cat'] = popular_job_dict[country][year]

# The 'df' dataset will now have updated 'most_popular_job_cat' values where 'age_group_simp' is 'Total'.
df

MemoryError: Unable to allocate 414. MiB for an array with shape (6, 9052604) and data type object